### ISSUE TITLE
[USER ISSUE] Encountered error while sending notification (SSLError: [Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by Oxyde59** [kvangent/PokeAlarm#363] opened 2017-03-30 09:50 UTC
## Problem Description

PokeAlarm work fine for month, but yesterday I install certbot (let's encrypt) to move my apache http -> https, and after a reboot, Pokealarm is down with this error : 

 Encountered error while sending notification (SSLError: [Errno 2] No such file or directory)
2017-03-30 11:18:23,701 [      manager_0][  Telegram][    INFO] Telegram is having connection issues. 1 attempt of 3.
2017-03-30 11:18:26,750 [      manager_0][  Telegram][   ERROR] Encountered error while sending notification (SSLError: [Errno 2] No such file or directory)
2017-03-30 11:18:26,750 [      manager_0][  Telegram][    INFO] Telegram is having connection issues. 2 attempt of 3.
...

## Your Environment
!--- Please post as many details  --
I'm on CentOS 7 
Python 2.7.5
apachectl -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Nov 14 2016 18:04:44

Did the issue persist after restarting the script yes

## Console Output
!--- Please post any relevant output provided from the PokeAlarm when you ran it --
```
	CONSOLE OUTPUT GOES HERE
```

## Your Alarms Config

/

## Troubleshooting Checklist
[x ] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x ] Checked the Wiki page for service in question

I try to uninstall / install requirements.txt

**Comment by kvangent** [comment] 2017-03-30 13:41
This is almost certainly not a bug, but something that was done incorrectly during the installation of Certbot. A possible explanation is that you either deleted or changed the access of a SSL cert that Telebot was using. If you just changed the access to it, the problem may go away by running PA as sudo. If you deleted it, the problem might be fixed by reinstalling the python modules with pip.

**Closed** 2017-04-02 13:31 UTC
