### ISSUE TITLE
[BUG] Triple notification in Telegram

### ISSUE THREAD

**Issue by Oxyde59** [kvangent/PokeAlarm#298] opened 2017-01-28 10:23 UTC
Hi !
 
since a week, my notif on telegram send me 3 messages (1 for the sticker, 1 for the txt, 1 for the map) instead of only one (the text) i have before
I don't understand, i change nothing on pokealarm nor in telegram
what could it be ?
I'll joined a screenshot later from my phone.

**Comment by Oxyde59** [comment] 2017-01-28 10:29
Example : 
![img_4031](https://cloud.githubusercontent.com/assets/11292569/22395951/ed390afa-e54c-11e6-8bc2-5961d7df2def.PNG)

**Comment by Faileador** [comment] 2017-01-28 14:30
This is not a bug. Your current notification is configured to send you 3 messages:

1) with sticker
2) message with pokemon details
3) last message with map

**Comment by Oxyde59** [comment] 2017-01-28 17:18
Have u read my message ? Before last week, i've got only one notification for the text message. I use Pokealarm for months and it's a recent change.

**Comment by kvangent** [comment] 2017-01-28 19:11
@Oxyde59 In the future, I would prefer you stick to the issue template.

This is an issue on Telegrams end and didn't come from a change in PokeAlarm. I will look into a work around.

**Comment by kvangent** [comment] 2017-02-05 21:37
@Oxyde59 It doesn't look like there is anything I can do from the PokeAlarm side. Per the telegram documentation disable_notficiations does the following
`Sends the message silently. iOS users will not receive a notification, Android users will receive a notification with no sound.`

So while I have disabled the sound, there isn't anything I can do to disable the notification. You can try asking Telegram for a solution, but I don't know if they are willing. 

I am going to close this for now. If you find some way around it, please let me know and I'll try to implement it.

**Closed by kvangent** 2017-02-05 21:37 UTC
Labels: enhancement
